export const API_KEY_CONFIG = 'API_KEY_CONFIG';
export const SEARCH_RESULT = 'SEARCH_RESULT';
export const POST_SEARCH_RESULT = 'POST_SEARCH_RESULT';
export const SEARCH_TEXT_REDUCER = 'SEARCH_TEXT_REDUCER';
export const SET_MEDIA_TYPE_MOVIE = 'SET_MEDIA_TYPE_MOVIE';
export const SET_MEDIA_TYPE_TV = 'SET_MEDIA_TYPE_TV';