export const API_KEY_CONFIG = 'API_KEY_CONFIG';
export const SEARCH_RESULT = 'SEARCH_RESULT';
export const POST_SEARCH_RESULT = 'POST_SEARCH_RESULT';
export const SEARCH_TEXT_REDUCER = 'SEARCH_TEXT_REDUCER';